name: Build

on:
  workflow_dispatch:
    inputs:
      downloadURL:
        description: 'totalDataFile Download URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with: 
        node-version: '14.x'
    - run: npm install
    - name: Get Data
      run: rm final_data.json && wget -O ./final_data.json ${{ github.event.inputs.downloadURL }}
      working-directory: ./src/data/
    - run: npm run build
    # - uses: w9jds/firebase-action@v1.5.0
    #   with:
    #     args: deploy
    #   env:
    #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
