name: Build

on:
  workflow_dispatch:
    inputs:
      downloadURL:
        description: 'totalDataFile Download URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with: 
        node-version: '14.x'
    - run: ls
    - run: cd src
    - run: ls
    - run: cd data
    - run: ls
    - run: rm final_data.json
    - run: wget -O ./final_data.json ${{ github.event.inputs.downloadURL }}
    - run: cd .. && cd ..
    - run: npm run build
    # - uses: w9jds/firebase-action@v1.5.0
    #   with:
    #     args: deploy
    #   env:
    #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
